export const Metrics = {
   border: {
      small: 1,
      medium: 2,
      large: 4,
   },
   font_size: {
      xxx_small: 12,
      xx_small: 14,
      x_small: 16,
      small: 20,
      medium: 24,
      large: 28,
      x_large: 32,
      xx_large: 36,
      xxx_large: 40,
   },
   opacity: {
      1: 0.1,
      2: 0.2,
      3: 0.6,
      4: 0.9,
   },
   radius: {
      xx_small: 4,
      x_small: 8,
      small: 12,
      medium: 24,
      x_large: 100,
   },
   spacing: {
      xxx_small: 4,
      xx_small: 8,
      x_small: 12,
      small: 16,
      medium: 24,
      large: 32,
      x_large: 40,
      xx_large: 48,
      xxx_large: 64,
   },
   thickness: {
      small: 1,
      medium: 2,
      large: 4,
   },
}
